# Generated by Django 2.0.9 on 2018-10-26 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('aadhar', models.BigIntegerField()),
                ('typeofcollector', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickUpRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofwaste', models.IntegerField()),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_date', models.DateTimeField(blank=True, null=True)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requestor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('aadhar', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pickup',
            name='name',
        ),
        migrations.DeleteModel(
            name='PickUp',
        ),
    ]
